name: Deploy App to GitHub Pages
on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
defaults:
  run:
    working-directory: frontend
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build
        env:
          VUE_APP_BASE_PATH: /spotify-playlist-creater/
      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          cname: spoti.fish 

